name:                 Project
version:              0.1.0.0
visibility:           public
id:                   Project-0.1.0.0-inplace
key:                  Project-0.1.0.0-inplace
license:              BSD-3-Clause
author:               Tomas
category:             Game
abi:                  inplace
exposed:              True
exposed-modules:      Graphics Logic Types
import-dirs:
    "/Users/Tomas/Documents/Spring 25/CS357/Project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/Project-0.1.0.0/build"

library-dirs:
    "/Users/Tomas/Documents/Spring 25/CS357/Project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/Project-0.1.0.0/build"

library-dirs-static:
    "/Users/Tomas/Documents/Spring 25/CS357/Project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/Project-0.1.0.0/build"

dynamic-library-dirs:
    "/Users/Tomas/Documents/Spring 25/CS357/Project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/Project-0.1.0.0/build"

data-dir:             "/Users/Tomas/Documents/Spring 25/CS357/Project/."
hs-libraries:         HSProject-0.1.0.0-inplace
depends:
    base-4.17.2.1 brll-1.13.3-b032ab97 rndm-1.3.1-b6dcb2d6

haddock-interfaces:
    "/Users/Tomas/Documents/Spring 25/CS357/Project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/Project-0.1.0.0/doc/html/Project/Project.haddock"

haddock-html:
    "/Users/Tomas/Documents/Spring 25/CS357/Project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/Project-0.1.0.0/doc/html/Project"
